// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	habit_tracker "habit-tracker"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GoalRepository is an autogenerated mock type for the GoalRepository type
type GoalRepository struct {
	mock.Mock
}

// InsertGoals provides a mock function with given fields: ctx, habits, now
func (_m *GoalRepository) InsertGoals(ctx context.Context, habits habit_tracker.Goals, now time.Time) error {
	ret := _m.Called(ctx, habits, now)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, habit_tracker.Goals, time.Time) error); ok {
		r0 = rf(ctx, habits, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGoals provides a mock function with given fields: ctx, habits, now
func (_m *GoalRepository) UpdateGoals(ctx context.Context, habits habit_tracker.Goals, now time.Time) error {
	ret := _m.Called(ctx, habits, now)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, habit_tracker.Goals, time.Time) error); ok {
		r0 = rf(ctx, habits, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGoalRepository creates a new instance of GoalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoalRepository {
	mock := &GoalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
